git:
  # branchLogCmd: "git log --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  # allBranchesLogCmd: "git log --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium "
  log:
    showGraph: "when-maximised"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editCommand: "nvim" # see 'Configuring File Editing' section
customCommands:
  - key: "w"
    prompts:
      - type: "input"
        title: "git commit skip hooks"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "files"
    subprocess: true
