local M = {
	-- coding
	autopairs = true,
	comment = true,
	tabout = true,
	todo_comments = true,
	vim_surround = true,
	comment_string = true,
	visual_multi = true,
	trevJ = true,
	trouble = false,
	lspsaga = true,
	fugitive = false,
	gitsigns = true,
	diffview = true,
	lazygit = true,
	dap = true,
	treesitter = true,
	telescope = true,
	project = false,
	neotest = false,
	-- ui
	mini = true,
	lualine = false,
	focus = false,
	dashboard = false,
	noice = true,
	notify = false,
	barbar = false,
	twilight = false,
	window_picker = false,
	zen = false,
	--editor
	lastplace = false,
	flit = false,
	flash = true,
	which_key = false,
	harpoon = true,
	bqf = true,
	formatter = true,
	bookmarks = true,
	fzf = true,
	-- lang
	go = false,
	-- lsp
	lsp = true,
	tstools = false,
	supermaven = true,
}

return M
