local M = {
	-- coding
	autopairs = true,
	comment = true,
	tabout = false,
	todo_comments = false,
	vim_surround = true,
	comment_string = true,
	visual_multi = true,
	trevJ = true,
	trouble = false,
	lspsaga = false,
	fugitive = false,
	gitsigns = true,
	diffview = false,
	lazygit = false,
	dap = false,
	treesitter = true,
	telescope = true,
	project = false,
	neotest = false,
	-- ui
	mini = true,
	lualine = false,
	focus = false,
	dashboard = false,
	noice = false,
	notify = false,
	barbar = false,
	twilight = false,
	window_picker = false,
	zen = false,
	--editor
	lastplace = false,
	flit = true,
	flash = false,
	which_key = false,
	harpoon = false,
	bqf = true,
	formatter = true,
	bookmarks = true,
	fzf = false,
	-- lang
	go = false,
	-- lsp
	lsp = true,
	tstools = true,
	supermaven = true,
}

return M
