local M = {
	-- coding
	autopairs = true,
	comment = true,
	tabout = true,
	todo_comments = true,
	vim_surround = true,
	comment_string = true,
	visual_multi = true,
	trevJ = true,
	trouble = false,
	lspsaga = true,
	fugitive = false,
	gitsigns = true,
	diffview = true,
	lazygit = true,
	dap = false,
	treesitter = true,
	telescope = true,
	project = true,
	neotest = false,
	-- ui
	mini = true,
	lualine = true,
	focus = false,
	dashboard = true,
	noice = true,
	notify = true,
	barbar = true,
	twilight = false,
	window_picker = true,
	zen = true,
	--editor
	lastplace = true,
	flit = true,
	flash = true,
	which_key = true,
	harpoon = true,
	bqf = true,
	formatter = true,
	bookmarks = true,
	fzf = true,
	-- lang
	go = true,
	-- lsp
	lsp = true,
	tstools = true,
	supermaven = true,
	maasha = true,
}

return M
